In [1]:
import pandas as pd
import numpy as np

In [2]:
products = pd.read_csv('products.csv')
products

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,NaN,NaN
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,NaN,1.0
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,1.0,1.0
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,NaN
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,NaN
...,...,...,...,...,...,...,...,...,...
1555,1556,CDR,CDR Creamy Peanut Butter,29538288712,2.65,1.14,6.94,1.0,1.0
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,1.0,NaN
1557,1558,CDR,CDR Extra Chunky Peanut Butter,84930775761,2.16,0.82,11.50,NaN,1.0
1558,1559,CDR,CDR Apple Preserves,75317577719,1.62,0.62,21.00,NaN,NaN
1559,1560,CDR,CDR Grape Jelly,54896665215,1.60,0.74,12.50,NaN,1.0

In [3]:
products.isna().sum()

product_id                 0
product_brand              0
product_name               0
product_sku                0
product_retail_price       0
product_cost               0
product_weight             0
recyclable               687
low_fat                 1008
dtype: int64

In [4]:
products['recyclable'].unique()

array([nan,  1.])

In [5]:
products.loc[products['recyclable'].isna() == True] = products.loc[products['recyclable'].isna() == True].fillna(0)

In [6]:
products['low_fat'].unique()

array([ 0.,  1., nan])

In [7]:
products.loc[products['low_fat'].isna() == True]

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,NaN
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,NaN
6,7,Washington,Washington Diet Cola,20191444754,2.61,0.91,18.00,1.0,NaN
7,8,Washington,Washington Orange Juice,89770532250,2.59,0.80,8.97,1.0,NaN
9,10,Washington,Washington Apple Juice,22114084362,1.42,0.50,8.13,1.0,NaN
...,...,...,...,...,...,...,...,...,...
1546,1547,CDR,CDR Pepper,48081826567,2.38,1.09,16.10,1.0,NaN
1547,1548,CDR,CDR Low Fat Apple Butter,80038576722,0.67,0.22,21.00,1.0,NaN
1551,1552,CDR,CDR Apple Jelly,15396953225,2.70,1.30,21.40,1.0,NaN
1552,1553,CDR,CDR Grape Jam,31972586512,1.86,0.87,13.50,1.0,NaN
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,1.0,NaN

In [8]:
products.loc[(products['low_fat'].isna() == True) & (products['product_name'].str.contains('Low Fat'))]

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
42,43,Club,Club Low Fat Cottage Cheese,18711594939,1.67,0.55,17.70,1.0,NaN
216,217,Best Choice,Best Choice Low Fat Cookies,19498726725,0.68,0.29,16.00,1.0,NaN
392,393,Big Time,Big Time Low Fat Waffles,48718068003,1.12,0.36,21.50,1.0,NaN
550,551,Fast,Fast Low Fat Chips,66810898184,3.21,1.12,7.87,1.0,NaN
703,704,Imagine,Imagine Low Fat Waffles,90773978829,1.63,0.73,8.41,1.0,NaN
841,842,Nationeel,Nationeel Low Fat BBQ Chips,42178552746,3.20,1.38,18.90,1.0,NaN
1003,1004,American,American Low Fat Bologna,39077082276,2.87,0.98,15.80,1.0,NaN
1023,1024,PigTail,PigTail Low Fat French Fries,75605292916,3.95,1.46,7.54,1.0,NaN
1297,1298,Booker,Booker Low Fat String Cheese,43085353970,1.34,0.43,6.30,1.0,NaN
1317,1318,Lake,Lake Low Fat Cole Slaw,22926171422,0.93,0.34,14.40,1.0,NaN
1330,1331,Carrington,Carrington Low Fat Waffles,95429553389,2.74,0.85,10.30,1.0,NaN
1465,1466,Fort West,Fort West Low Fat Cookies,62315633893,1.80,0.61,11.70,1.0,NaN
1488,1489,Fort West,Fort West Low Fat Chips,18948981165,1.73,0.78,13.30,1.0,NaN
1547,1548,CDR,CDR Low Fat Apple Butter,80038576722,0.67,0.22,21.00,1.0,NaN

A data quality issue was also identified in the low_fat column, where a subset of products had a missing (NaN) value instead of a defined 0 or 1. Rather than treating these as equivalent to "not low fat," the missing values were treated as "unknown," since no reliable source (numeric flag or product name) confirmed the product's classification. Where the product name explicitly contained the phrase "Low Fat," the value was inferred and corrected to 1; the remaining unresolved records were flagged as "Unknown" for further review.

In [9]:
products.loc[(products['low_fat'].isna() == True) & (products['product_name'].str.contains('Low Fat')),"low_fat"] = 1

In [10]:
products.loc[(products['product_name'].str.contains('Low Fat')) & (products['low_fat'] == 0)]

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
48,49,Club,Club Low Fat String Cheese,68700224757,3.38,1.42,17.00,0.0,0.0
230,231,Best Choice,Best Choice Low Fat Popcorn,14413666129,2.65,1.01,10.00,0.0,0.0
298,299,Super,Super Low Fat Apple Butter,80255631804,1.68,0.77,16.60,0.0,0.0
353,354,Carlson,Carlson Low Fat Cottage Cheese,35180862545,2.25,0.72,9.77,0.0,0.0
354,355,Carlson,Carlson Low Fat Sour Cream,87092131972,0.81,0.34,12.20,0.0,0.0
376,377,Moms,Moms Low Fat Bologna,24599472880,2.10,0.71,18.00,0.0,0.0
396,397,Big Time,Big Time Low Fat French Fries,67432805895,1.35,0.46,12.00,0.0,0.0
664,665,Gorilla,Gorilla Low Fat Cottage Cheese,33163658976,1.57,0.64,8.79,0.0,0.0
690,691,Cutting Edge,Cutting Edge Low Fat Cole Slaw,86293048262,2.85,1.23,9.66,0.0,0.0
838,839,Nationeel,Nationeel Low Fat Cookies,40255913138,0.66,0.30,14.40,0.0,0.0
861,862,Nationeel,Nationeel Low Fat Chips,12006705403,2.73,1.06,9.70,0.0,0.0
980,981,Even Better,Even Better Low Fat Cottage Cheese,31726981997,1.27,0.44,19.70,0.0,0.0
981,982,Even Better,Even Better Low Fat Sour Cream,65970433354,2.88,1.04,12.30,0.0,0.0
986,987,Even Better,Even Better Low Fat String Cheese,42023038268,2.59,1.14,18.60,0.0,0.0
1019,1020,PigTail,PigTail Low Fat Waffles,50246916413,0.51,0.19,14.70,0.0,0.0
1154,1155,Horatio,Horatio Low Fat Cookies,11329383254,1.88,0.81,16.10,0.0,0.0
1168,1169,Horatio,Horatio Low Fat Popcorn,32649618983,2.98,1.13,15.10,0.0,0.0
1177,1178,Horatio,Horatio Low Fat Chips,11555708050,3.78,1.78,10.50,0.0,0.0
1291,1292,Booker,Booker Low Fat Cottage Cheese,54668398499,3.33,1.60,18.50,0.0,0.0
1334,1335,Carrington,Carrington Low Fat French Fries,92312397360,2.41,0.94,8.15,0.0,0.0
1468,1469,Fort West,Fort West Low Fat BBQ Chips,66115648150,2.13,0.72,19.30,0.0,0.0

In [11]:
products.loc[(products['product_name'].str.contains('Low Fat')) & (products['low_fat'] == 0)].shape

(21, 9)

A Data inconsistency was identified in 21 products where the product name contains "Low Fat" while the corresponding low_fat column value is recorded as 0 this represents a conflict between two fields that are expected to reflect the same attribute indicating a possible error in data entry or an update that was applied to one source but not the other.

In [12]:
products.loc[(products['product_name'].str.contains('Low Fat')) & (products['low_fat'] == 0),"low_fat"] = 1

In [13]:
products.isna().sum()

product_id                0
product_brand             0
product_name              0
product_sku               0
product_retail_price      0
product_cost              0
product_weight            0
recyclable                0
low_fat                 560
dtype: int64

In [14]:
products['low_fat'] = products['low_fat'].replace({0: 'no', 1: 'yes'})

In [15]:
products.loc[products['low_fat'].isna() == True,'low_fat'] = 'Unknown'

In [16]:
products.isna().sum()

product_id              0
product_brand           0
product_name            0
product_sku             0
product_retail_price    0
product_cost            0
product_weight          0
recyclable              0
low_fat                 0
dtype: int64

In [17]:
products.loc[products['recyclable'].isna() == True] = products.loc[products['recyclable'].isna() == True].fillna(0)

In [18]:
products.drop_duplicates(inplace=True)

In [19]:
Q1 = products['product_retail_price'].quantile(0.25)
Q3 = products['product_retail_price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = products[(products['product_retail_price'] < lower_bound) | 
                     (products['product_retail_price'] > upper_bound)]
outliers

Empty DataFrame
Columns: [product_id, product_brand, product_name, product_sku, product_retail_price, product_cost, product_weight, recyclable, low_fat]
Index: []

no outliers

In [20]:
products.to_csv('C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\retail company\\cleaned datasets\\products.csv', index=False)